//------------------------------------------------------------------------------
// <auto-generated>
//     Il codice è stato generato da uno strumento.
//     Versione runtime:4.0.30319.42000
//
//     Le modifiche apportate a questo file possono provocare un comportamento non corretto e andranno perse se
//     il codice viene rigenerato.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsApp.Properties {
    using System;
    
    
    /// <summary>
    ///   Classe di risorse fortemente tipizzata per la ricerca di stringhe localizzate e così via.
    /// </summary>
    // Questa classe è stata generata automaticamente dalla classe StronglyTypedResourceBuilder.
    // tramite uno strumento quale ResGen o Visual Studio.
    // Per aggiungere o rimuovere un membro, modificare il file con estensione ResX ed eseguire nuovamente ResGen
    // con l'opzione /str oppure ricompilare il progetto VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Restituisce l'istanza di ResourceManager nella cache utilizzata da questa classe.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("WindowsFormsApp.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Esegue l'override della proprietà CurrentUICulture del thread corrente per tutte le
        ///   ricerche di risorse eseguite utilizzando questa classe di risorse fortemente tipizzata.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Veicoli.accdb.
        /// </summary>
        public static string ACCESS_DB_NAME {
            get {
                return ResourceManager.GetString("ACCESS_DB_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una risorsa localizzata di tipo System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap ADD_ICON {
            get {
                object obj = ResourceManager.GetObject("ADD_ICON", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Cerca una risorsa localizzata di tipo System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap CAR_ICON {
            get {
                object obj = ResourceManager.GetObject("CAR_ICON", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Cerca una risorsa localizzata di tipo System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap CLOSE_BTN_ICON {
            get {
                object obj = ResourceManager.GetObject("CLOSE_BTN_ICON", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a .\www.
        /// </summary>
        public static string DATAS_PATH {
            get {
                return ResourceManager.GetString("DATAS_PATH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una risorsa localizzata di tipo System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap EXPORTDB_ICON {
            get {
                object obj = ResourceManager.GetObject("EXPORTDB_ICON", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Cerca una risorsa localizzata di tipo System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap EXPORTDOCX_ICON {
            get {
                object obj = ResourceManager.GetObject("EXPORTDOCX_ICON", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Cerca una risorsa localizzata di tipo System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap EXPORTXSLX_ICON {
            get {
                object obj = ResourceManager.GetObject("EXPORTXSLX_ICON", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a .\files.
        /// </summary>
        public static string FILES_PATH {
            get {
                return ResourceManager.GetString("FILES_PATH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una risorsa localizzata di tipo System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap HISTORY_ICON {
            get {
                object obj = ResourceManager.GetObject("HISTORY_ICON", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a .\www\images.
        /// </summary>
        public static string IMAGE_FOLDER_PATH {
            get {
                return ResourceManager.GetString("IMAGE_FOLDER_PATH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una risorsa localizzata di tipo System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap MOTO_ICON {
            get {
                object obj = ResourceManager.GetObject("MOTO_ICON", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Cerca una risorsa localizzata di tipo System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap NOIMG_ICON {
            get {
                object obj = ResourceManager.GetObject("NOIMG_ICON", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Cerca una risorsa localizzata di tipo System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap OPEN_BTN_ICON {
            get {
                object obj = ResourceManager.GetObject("OPEN_BTN_ICON", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Cerca una risorsa localizzata di tipo System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap PRINT_ICON {
            get {
                object obj = ResourceManager.GetObject("PRINT_ICON", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a SALONE VENDITA VEICOLI NUOVI E USATI.
        /// </summary>
        public static string PROGRAM_NAME {
            get {
                return ResourceManager.GetString("PROGRAM_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una risorsa localizzata di tipo System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap SAVE_ICON {
            get {
                object obj = ResourceManager.GetObject("SAVE_ICON", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Cerca una risorsa localizzata di tipo System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap SEARCH_ICON {
            get {
                object obj = ResourceManager.GetObject("SEARCH_ICON", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Cerca una risorsa localizzata di tipo System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap SETTINGS_ICON {
            get {
                object obj = ResourceManager.GetObject("SETTINGS_ICON", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Cerca una risorsa localizzata di tipo System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap WEB_ICON {
            get {
                object obj = ResourceManager.GetObject("WEB_ICON", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Cerca una risorsa localizzata di tipo System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap WEB2_ICON {
            get {
                object obj = ResourceManager.GetObject("WEB2_ICON", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
